[cs]
  languageName = "Czech"
  contentDir = "content/cs"
  weight = 10
  [cs.params]
    languageISO = "CS"
    languageTag = "cs-CZ"
    footer = ''
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
